### ISSUE TITLE
Use IDictionary<string, object> for Properties (eg in Thing)

### ISSUE THREAD

**Issue by DLade** [gost/sensorthings-net-sdk#10]
The structur IDictionary<string, object> fits best for properties.

I tried it with very different types (double, string,..) the de-/serialization works fine.

**Comment by bertt** [comment]
yes good catch, fixed in https://github.com/gost/sensorthings-net-sdk/commit/3e18f6187ca324d27d735b6de5f378a534f7338c
If I remember well other entities (besides Thing) now also have properties, they can use the same structure when added.
