### ISSUE TITLE
Idea: Use Type instead of EntityType

### ISSUE THREAD

**Issue by DLade** [gost/sensorthings-net-sdk#12]
With a simple trick you could remove two classes (EntityType and partly EntityMapping) and have simpler code, by replacing the EntityType for the real Type.

see
https://github.com/gost/sensorthings-net-sdk/compare/master...iteratec:feature/try-class-instead-of-enum

What do you think?

**Comment by bertt** [comment]
yes good idea, can you make a PR with deleting code EntityType and partly EntityMapping?

**Comment by DLade** [comment]
yes I can :-)
