### ISSUE TITLE
Fix mixed namespaces

### ISSUE THREAD

**Issue by DLade** [gost/sensorthings-net-sdk#19]
The namespaces are sometimes mixed in cases (lower vs upper case). This is very confusing.

eg. `sensorthings.ODATA` vs `SensorThings.Core`
eg. `sensorthings.Core` vs `SensorThings.Core`

Guess the best C# way is using camel-case at all (eg. `SensorThings.Core`)

Note: The same with directories in the project (eg. `Core` vs `client` vs `ODATA`)

**Comment by DLade** [comment]
see pull-request: https://github.com/gost/sensorthings-net-sdk/pull/24

**Comment by DLade** [comment]
You merged it? Nice!

BTW, can you push the new version to nuget, please?

**Comment by bertt** [comment]
Yes 0.4 is now on NuGet!

Btw: I've added you as developer in this repository
