### ISSUE TITLE
Add support for post location and request trail

### ISSUE THREAD

**Issue by bertt** [gost/sensorthings-net-sdk#2]

**Comment by DLade** [comment]
FYI

For Locations I simply create a JObject and put it there:
```
return new Location {
    Name = name,
    Description = description,
    EncodingType = "application/geo+json",
    Feature = JObject.Parse(
        $"{{\"type\": \"Point\", \"coordinates\": [{longitude}, {latitude}]}}"),
};
```
This is helpful if you don't like to implement the whole GeoJson-Interface and need just a Point, like me.

**Comment by DLade** [comment]
@bertt Can you help me to find out what this issue is about?

**Comment by bertt** [comment]
This was about a specific usecase: using SensorThings for storing device positions (like gps), store all kind of device parameters (like device temperature) and visualize the trail with measured parameters on a map in a .NET client. 
But I'm not working on this so I think we can close this issue.

**Comment by DLade** [comment]
@bertt What do you mean by that? Can you give more details, please?

note: POST comes
