### ISSUE TITLE
Typo in test data

### ISSUE THREAD

**Issue by DLade** [gost/sensorthings-net-sdk#7]
Hi I've found a little typo in your test data.

```
OGCSensorThings/v1.0/Locations(760795)
   "encodingType": "application/vnd.get+json",
```
The encodingType is "vnd.**geo**+json".

FYI:
* vnd.geo+json (OBSOLETED by [RFC7946] in favor of application/geo+json)
  (see [Media Types](https://www.iana.org/assignments/media-types/media-types.xhtml#application))

**Comment by bertt** [comment]
ok thanks, fixed it in https://github.com/gost/sensorthings-net-sdk/commit/1de5b1044c8bf543505f2828312574606b7d34aa
